apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: aggregated-pods
  labels:
    rbac.example.com/aggregate: "true"
# When you create the "aggregated-pods" ClusterRole,
# the rules below will be added to the "aggregator" ClusterRole.
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["*"]
