apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: aggregated-crb
subjects:
- kind: User
  name: maddy # Name is case sensitive
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: aggregator
  apiGroup: rbac.authorization.k8s.io
